### ISSUE TITLE
Rewrite using asyncio

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-wizard#18]

**Comment by glasserc** [comment]
Wouldn't this mean rewriting kinto-http.py using asyncio as well?

**Comment by leplatrem** [comment]
That wouldn't be a bad idea, but it is not necessary. We can use executors with thread or process pools in order to integrate blocking code with asyncio

**Comment by glasserc** [comment]
I'm closing this because I don't believe there is much value in replacing the `load` command with an implementation based on asyncio.
