### ISSUE TITLE
Add support for DateTime and Date json encoding.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-wizard#50]
```
TypeError: datetime.date(2018, 7, 15) is not JSON serializable
```

I have to say, I am a bit sad about that. No problem to export the datetime as yaml but then when it is loaded from YAML it reads it as a datetime and fails to make the object body.

**Comment by glasserc** [comment]
You exported a datetime as YAML? Where did the datetime come from? Probably not from Kinto because there's no JSON syntax for datetimes. You can express a datetime as a string (even in YAML) by doing e.g. `"2018-07-15"`.

**Comment by Natim** [comment]
That's what I did eventually, you mean the YAML wasn't compatible with kinto-wizard dump command? You are probably right.

**Comment by Natim** [comment]
```
>>> from io import StringIO
>>> s = StringIO()
>>> from ruamel.yaml import YAML
>>> y = YAML()
>>> import json
>>> y.dump({"data": date.today()}, s)
>>> s.getvalue()
'data: 2018-06-22\n'
>>> s.seek(0)
>>> p = y.load(s)
>>> p
CommentedMap([('data', datetime.date(2018, 6, 22))])
>>> json.dump(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'date' is not JSON serializable

```

**Comment by Natim** [comment]
A simple way to handle that would be:

```
>>> from datetime import date, datetime
>>> def json_serial(obj):
...     """JSON serializer for objects not serializable by default json code"""
...     if isinstance(obj, (datetime, date)):
...         return obj.isoformat()
...     raise TypeError ("Type %s not serializable" % type(obj))
... 
>>> json.dumps(p, default=json_serial)
'{"data": "2018-06-22"}'
```

**Comment by glasserc** [comment]
> The question is, should we handle case when we try to load a YAML that contains a string that is decoded as a Date or Datetime object and then fail

I don't understand why we would treat Date or Datetime any different than the other types that are expressible in YAML and not in JSON (for instance, sets, or dicts with the keys not being strings). I would expect these to fail because there is no way to store them.

> or should we encode it as the same string it was inside the YAML?

Your proposed solution doesn't do that, though -- it converts it to ISO8601 format, regardless of the string it was encoded as in YAML. In general, I'm nervous about software that silently converts user data.

**Comment by Natim** [comment]
> it converts it to ISO8601 format, regardless of the string it was encoded as in YAML
Note that the encoding in a YAML file is standard: https://symfony.com/doc/current/components/yaml/yaml_format.html#dates
